In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

DATA_DIR = Path("/Users/akkouh/Desktop/polybase")  # à adapter selon ton dossier
excel_files = sorted(DATA_DIR.glob("Suivi_*.xlsx"))

excel_files

[PosixPath('/Users/akkouh/Desktop/polybase/Suivi_2019.xlsx'),
 PosixPath('/Users/akkouh/Desktop/polybase/Suivi_2020.xlsx'),
 PosixPath('/Users/akkouh/Desktop/polybase/Suivi_2021.xlsx'),
 PosixPath('/Users/akkouh/Desktop/polybase/Suivi_2022.xlsx'),
 PosixPath('/Users/akkouh/Desktop/polybase/Suivi_2023.xlsx'),
 PosixPath('/Users/akkouh/Desktop/polybase/Suivi_2024.xlsx'),
 PosixPath('/Users/akkouh/Desktop/polybase/Suivi_2025.xlsx'),
 PosixPath('/Users/akkouh/Desktop/polybase/Suivi_2026.xlsx')]

In [3]:
# Vérifier les feuilles disponibles dans chaque fichier Excel

for file in excel_files:
    xls = pd.ExcelFile(file)
    print(f"\n{file.name}")
    print(xls.sheet_names)

Suivi_2019.xlsx
['Aurelia', 'Hydrozoa', 'Cubozoa', 'Rhizostomae', 'Semaestomeae', 'Coronatae']

Suivi_2020.xlsx
['Aurelia', 'Cubozoa', 'Hydrozoa', 'Rhizostomae', 'Semaestomeae', 'Coronatae']

Suivi_2021.xlsx
['Aurelia', 'Cubozoa', 'Hydrozoa', 'Rhizostomae', 'Semaestomeae', 'Coronatae']

Suivi_2022.xlsx
['Aurelia', 'Cubozoa', 'Hydrozoa', 'Rhizostomae', 'Semaestomeae', 'Coronatae']

Suivi_2023.xlsx
['Aurelia', 'Hydrozoa', 'Cubozoa', 'Rhizostomeae', 'Semaestomeae', 'Coronatae', 'UMR_MARBEC']

Suivi_2024.xlsx
['Aurelia', 'Hydrozoa', 'Cubozoa', 'Rhizostomae', 'Semaestomeae', 'Feuil1', 'Feuil2', 'Coronatae', 'UMR_MARBEC']

Suivi_2025.xlsx
['Aurelia', 'Hydrozoa', 'Cubozoa', 'Rhizostomae', 'Feuil1', 'Semaestomeae', 'Coronatae', 'Staurozoa', 'UMR_MARBEC']

Suivi_2026.xlsx
['Aurelia', 'Hydrozoa', 'Cubozoa', 'Rhizostomae', 'Feuil1', 'Semaestomeae', 'Coronatae']

In [4]:
# Aperçu des feuilles d'un fichier exemple

file_example = excel_files[1]  # Suivi_2020.xlsx
xls = pd.ExcelFile(file_example)

for sheet in xls.sheet_names:
    print("\n" + "=" * 80)
    print(f"Fichier : {file_example.name} | Feuille : {sheet}")
    df = pd.read_excel(file_example, sheet_name=sheet, header=None)
    display(df.head(10))

================================================================================
Fichier : Suivi_2020.xlsx | Feuille : Aurelia

,0,1,2,3,4,5,6,7,8,9,...,46,47,48,49,50,51,52,53,54,55
0,NaN,NaN,NaN,NaN,JANVIER,NaN,NaN,NaN,NaN,FEVRIER,...,NaN,NaN,NOVEMBRE,NaN,NaN,NaN,DECEMBRE,NaN,NaN,NaN
1,Espèce,N° boîte,Température (°C),NaN,1,2.0,3.0,4.0,5.0,6,...,43.0,44.0,45,46.0,47.0,48.0,49,50.0,51.0,52.0
2,Aurelia labiata,ALA-JKA-1.02,5,Nb polypes,200,200.0,200.0,200.0,200.0,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Nb éphyrules,200,200.0,200.0,200.0,200.0,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,15,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,200.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,ALA-JKA-1.03,5,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,200.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,15,Nb polypes,50,50.0,100.0,50.0,100.0,100,...,NaN,NaN,100,200.0,200.0,200.0,200,200.0,200.0,200.0
9,NaN,NaN,NaN,Nb éphyrules,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,12,1.0,0.0,0.0,0,0.0,0.0,0.0

================================================================================
Fichier : Suivi_2020.xlsx | Feuille : Cubozoa

,0,1,2,3,4,5,6,7,8,9,...,46,47,48,49,50,51,52,53,54,55
0,NaN,NaN,NaN,NaN,JANVIER,NaN,NaN,NaN,NaN,FEVRIER,...,NaN,NaN,NOVEMBRE,NaN,NaN,NaN,DECEMBRE,NaN,NaN,NaN
1,Espèce,N° boîte,Température (°C),NaN,1,2.0,3.0,4.0,5.0,6,...,43.0,44.0,45,46.0,47.0,48.0,49,50.0,51.0,52.0
2,Alatina morandinii,AMO-JKA-1.01,25,Nb polypes,200,200.0,200.0,100.0,200.0,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Nb éphyrules,3,50.0,0.0,50.0,0.0,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,50.0,50.0,50,100.0,50.0,50.0,50,50.0,50.0,50.0
5,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0
6,NaN,AMO-JKA-1.02,25,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,50.0,50.0,50,50.0,50.0,50.0,50,50.0,50.0,50.0
7,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0
8,NaN,NaN,30,Nb polypes,200,200.0,200.0,100.0,100.0,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,Nb éphyrules,50,50.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
Fichier : Suivi_2020.xlsx | Feuille : Hydrozoa

,0,1,2,3,4,5,6,7,8,9,...,46,47,48,49,50,51,52,53,54,55
0,NaN,NaN,NaN,NaN,JANVIER,NaN,NaN,NaN,NaN,FEVRIER,...,NaN,NaN,NOVEMBRE,NaN,NaN,NaN,DECEMBRE,NaN,NaN,NaN
1,Espèce,N° boîte,Température (°C),NaN,1,2.0,3.0,4.0,5.0,6,...,43.0,44.0,45,46.0,47.0,48.0,49,50.0,51.0,52.0
2,Aequorea coerulescens,ACO-JKA-2.01,10,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,200.0,200.0,200,200.0,200.0,200.0,200,200.0,200.0,200.0
3,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,200.0,100.0,0,100.0,200.0,200.0,200,50.0,100.0,50.0
4,NaN,NaN,15,Nb polypes,100,100.0,100.0,100.0,100.0,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,Nb éphyrules,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,ACO-JKA-2.02,10,Nb polypes,100,100.0,100.0,100.0,100.0,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,Nb éphyrules,0,0.0,50.0,0.0,0.0,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,15,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,200.0,200.0,200,200.0,200.0,100.0,200,200.0,200.0,200.0
9,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0

================================================================================
Fichier : Suivi_2020.xlsx | Feuille : Rhizostomae

,0,1,2,3,4,5,6,7,8,9,...,46,47,48,49,50,51,52,53,54,55
0,NaN,NaN,NaN,NaN,JANVIER,NaN,NaN,NaN,NaN,FEVRIER,...,NaN,NaN,NOVEMBRE,NaN,NaN,NaN,DECEMBRE,NaN,NaN,NaN
1,Espèce,N° boîte,Température (°C),NaN,1,2.0,3.0,4.0,5.0,6,...,43.0,44.0,45,46.0,47.0,48.0,49,50.0,51.0,52.0
2,Cassiopea sp.,CSP-FPA-1.04,20,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,200.0,200.0,200,200.0,200.0,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,25,Nb polypes,200,50.0,100.0,200.0,200.0,200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,Nb éphyrules,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,CSP-FPA-1.05,20,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,25,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,100.0,100,100.0,100.0,100.0
9,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0,0.0,0.0,0.0

================================================================================
Fichier : Suivi_2020.xlsx | Feuille : Semaestomeae

,0,1,2,3,4,5,6,7,8,9,...,46,47,48,49,50,51,52,53,54,55
0,NaN,NaN,NaN,NaN,JANVIER,NaN,NaN,NaN,NaN,FEVRIER,...,NaN,NaN,NOVEMBRE,NaN,NaN,NaN,DECEMBRE,NaN,NaN,NaN
1,Espèce,N° boîte,Température (°C),NaN,1,2.0,3.0,4.0,5.0,6,...,43.0,44.0,45,46.0,47.0,48.0,49,50.0,51.0,52.0
2,Chrysaoa achlyos,CAC-JKA-1.01\n,15,Nb polypes,53,50.0,100.0,100.0,100.0,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Nb éphyrules,11,0.0,0.0,50.0,50.0,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,20,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,50.0,50.0,100,100.0,100.0,100.0,50,50.0,50.0,100.0
5,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,3.0,50,50.0,0.0,0.0,0,0.0,0.0,50.0
6,NaN,CAC-JKA-1.02,15,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,18.0,8.0,8,8.0,8.0,8.0,8,100.0,100.0,50.0
7,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,2.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0
8,NaN,NaN,20,Nb polypes,50,50.0,100.0,100.0,100.0,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,Nb éphyrules,100,50.0,0.0,50.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
Fichier : Suivi_2020.xlsx | Feuille : Coronatae

,0,1,2,3,4,5,6,7,8,9,...,46,47,48,49,50,51,52,53,54,55
0,NaN,NaN,NaN,NaN,JANVIER,NaN,NaN,NaN,NaN,FEVRIER,...,NaN,NaN,NOVEMBRE,NaN,NaN,NaN,DECEMBRE,NaN,NaN,NaN
1,Espèce,N° boîte,Température (°C),NaN,1,2.0,3.0,4.0,5.0,6,...,43.0,44.0,45,46.0,47.0,48.0,49,50.0,51.0,52.0
2,Linuche aquila,LAQ-JKA-1.01,25,Nb polypes,50,100.0,100.0,100.0,100.0,200,...,100.0,200.0,200,200.0,200.0,200.0,200,200.0,200.0,200.0
3,NaN,NaN,NaN,Nb éphyrules,0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0
4,NaN,NaN,30,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,LAQ-JKA-1.02,25,Nb polypes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,Nb éphyrules,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,30,Nb polypes,100,100.0,100.0,100.0,100.0,100,...,200.0,200.0,200,200.0,200.0,200.0,200,200.0,200.0,200.0
9,NaN,NaN,NaN,Nb éphyrules,0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0

In [5]:
import re
import pandas as pd
import numpy as np

def extract_year_from_filename(path):
    match = re.search(r"(\d{4})", path.name)
    return int(match.group(1)) if match else None


def clean_text(value):
    if pd.isna(value):
        return None
    return str(value).strip()


def normalize_measure_type(value):
    value = clean_text(value)
    if value is None:
        return None

    value_lower = value.lower()

    if "polype" in value_lower:
        return "polypes"
    if "éphyr" in value_lower or "ephyr" in value_lower:
        return "ephyrules"

    return value_lower


def parse_excel_file(file_path):
    year = extract_year_from_filename(file_path)
    xls = pd.ExcelFile(file_path)

    rows = []

    for sheet_name in xls.sheet_names:
        # On ignore les feuilles vides/génériques si besoin
        if sheet_name.lower().startswith("feuil"):
            continue

        df = pd.read_excel(file_path, sheet_name=sheet_name, header=None)

        # Les semaines sont sur la ligne 1, à partir de la colonne 4
        week_columns = []
        for col in range(4, df.shape[1]):
            week_value = df.iloc[1, col]

            if pd.notna(week_value):
                try:
                    week_number = int(float(week_value))
                    week_columns.append((col, week_number))
                except ValueError:
                    pass

        current_species = None
        current_box = None
        current_temperature = None

        # Les données commencent à la ligne 2
        for row_idx in range(2, df.shape[0]):
            species = clean_text(df.iloc[row_idx, 0])
            box = clean_text(df.iloc[row_idx, 1])
            temperature = df.iloc[row_idx, 2]
            measure_type = normalize_measure_type(df.iloc[row_idx, 3])

            # Propagation des valeurs fusionnées / vides
            if species is not None:
                current_species = species

            if box is not None:
                current_box = box

            if pd.notna(temperature):
                current_temperature = temperature

            if measure_type is None:
                continue

            for col, week_number in week_columns:
                value = df.iloc[row_idx, col]

                rows.append({
                    "annee": year,
                    "groupe": sheet_name,
                    "espece": current_species,
                    "code_boite": current_box,
                    "temperature_cible": current_temperature,
                    "semaine": week_number,
                    "type_mesure": measure_type,
                    "valeur": value,
                    "fichier_source": file_path.name,
                    "feuille_source": sheet_name,
                    "ligne_source": row_idx + 1,
                })

    return pd.DataFrame(rows)

In [6]:
tracking_long_df = pd.concat(
    [parse_excel_file(file) for file in excel_files],
    ignore_index=True
)

display(tracking_long_df.head(20))
tracking_long_df.shape

,annee,groupe,espece,code_boite,temperature_cible,semaine,type_mesure,valeur,fichier_source,feuille_source,ligne_source
0,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,1,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
1,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,2,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
2,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,3,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
3,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,4,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
4,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,5,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
5,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,6,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
6,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,7,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
7,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,8,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
8,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,9,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
9,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,10,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
10,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,11,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
11,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,12,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
12,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,13,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
13,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,14,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
14,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,15,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
15,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,16,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
16,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,17,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
17,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,18,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
18,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,19,polypes,NaN,Suivi_2019.xlsx,Aurelia,3
19,2019,Aurelia,Aurelia labiata,ALA-JKA-1.03,5,20,polypes,NaN,Suivi_2019.xlsx,Aurelia,3

(259688, 11)

In [13]:
print(tracking_long_df.shape)
print(tracking_long_df["type_mesure"].value_counts(dropna=False))

(259688, 11)
type_mesure
polypes      130052
ephyrules    129324
nb              312
Name: count, dtype: int64

In [14]:
tracking_non_empty_df = tracking_long_df[tracking_long_df["valeur"].notna()].copy()

display(tracking_non_empty_df.head(20))
tracking_non_empty_df.shape

,annee,groupe,espece,code_boite,temperature_cible,semaine,type_mesure,valeur,fichier_source,feuille_source,ligne_source
21528,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,1,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21529,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,2,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21530,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,3,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21531,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,4,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21532,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,5,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21533,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,6,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21534,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,7,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21535,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,8,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21536,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,9,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21537,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,10,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21538,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,11,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21542,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,15,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21546,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,19,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21550,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,23,polypes,100.0,Suivi_2020.xlsx,Aurelia,3
21551,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,24,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21552,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,25,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21554,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,27,polypes,200.0,Suivi_2020.xlsx,Aurelia,3
21580,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,1,ephyrules,200.0,Suivi_2020.xlsx,Aurelia,4
21581,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,2,ephyrules,200.0,Suivi_2020.xlsx,Aurelia,4
21582,2020,Aurelia,Aurelia labiata,ALA-JKA-1.02,5,3,ephyrules,200.0,Suivi_2020.xlsx,Aurelia,4

(76306, 11)

In [15]:
tracking_long_df.shape
tracking_long_df["type_mesure"].value_counts(dropna=False)
tracking_non_empty_df.shape

(76306, 11)

In [16]:
print("Espèces manquantes :", tracking_non_empty_df["espece"].isna().sum())
print("Boîtes manquantes :", tracking_non_empty_df["code_boite"].isna().sum())
print("Températures manquantes :", tracking_non_empty_df["temperature_cible"].isna().sum())
print("Valeurs manquantes :", tracking_non_empty_df["valeur"].isna().sum())

Espèces manquantes : 0
Boîtes manquantes : 0
Températures manquantes : 146
Valeurs manquantes : 0

In [17]:
nb_rows = tracking_long_df[tracking_long_df["type_mesure"] == "nb"].copy()

display(nb_rows[[
    "annee", "groupe", "espece", "code_boite",
    "temperature_cible", "semaine", "type_mesure",
    "valeur", "fichier_source", "feuille_source", "ligne_source"
]].head(50))

print(nb_rows["fichier_source"].value_counts())
print(nb_rows["feuille_source"].value_counts())
print(nb_rows["ligne_source"].value_counts().head(20))

,annee,groupe,espece,code_boite,temperature_cible,semaine,type_mesure,valeur,fichier_source,feuille_source,ligne_source
222976,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,1,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222977,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,2,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222978,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,3,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222979,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,4,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222980,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,5,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222981,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,6,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222982,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,7,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222983,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,8,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222984,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,9,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222985,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,10,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222986,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,11,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222987,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,12,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222988,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,13,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222989,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,14,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222990,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,15,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222991,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,16,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222992,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,17,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222993,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,18,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222994,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,19,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
222995,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,20,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
222996,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,21,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
222997,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,22,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
222998,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,23,nb,3,Suivi_2025.xlsx,Staurozoa,3
222999,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,24,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223000,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,25,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223001,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,26,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223002,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,27,nb,3,Suivi_2025.xlsx,Staurozoa,3
223003,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,28,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223004,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,29,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223005,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,30,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223006,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,31,nb,2,Suivi_2025.xlsx,Staurozoa,3
223007,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,32,nb,2,Suivi_2025.xlsx,Staurozoa,3
223008,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,33,nb,1.0,Suivi_2025.xlsx,Staurozoa,3
223009,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,34,nb,0.0,Suivi_2025.xlsx,Staurozoa,3
223010,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,35,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223011,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,36,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223012,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,37,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223013,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,38,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223014,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,39,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223015,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,40,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223016,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,41,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223017,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,42,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223018,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,43,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223019,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,44,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223020,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,45,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223021,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,46,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223022,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,47,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223023,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,48,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223024,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,49,nb,NaN,Suivi_2025.xlsx,Staurozoa,3
223025,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,50,nb,NaN,Suivi_2025.xlsx,Staurozoa,3

fichier_source
Suivi_2025.xlsx    312
Name: count, dtype: int64
feuille_source
Staurozoa    312
Name: count, dtype: int64
ligne_source
3    52
4    52
5    52
6    52
7    52
8    52
Name: count, dtype: int64

In [18]:
file_2025 = [f for f in excel_files if "2025" in f.name][0]

df_stauro = pd.read_excel(file_2025, sheet_name="Staurozoa", header=None)

display(df_stauro.head(15))

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,NaN,NaN,NaN,NaN,2024.0,JANVIER,NaN,NaN,NaN,FEVRIER,...,NaN,NOVEMBRE,NOVEMBRE,NaN,NaN,NaN,DECEMBRE,NaN,NaN,NaN
1,Espèce,N° boîte,Température (°C),NaN,NaN,1,2.0,3.0,4.0,5,...,43.0,44,45,46.0,47.0,48.0,49,50.0,51.0,52.0
2,Lucernaria quadricornis,LQU-NBE-1.01,10,Nb,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Nb,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Staurozoa sp.,STA-FPA-1.01,15,Nb,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,Nb,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,STA-FPA-1.02,15,Nb,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,Nb,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# Vérifier si la feuille Staurozoa contient des valeurs non vides
# dans les colonnes des semaines

week_values_stauro = df_stauro.iloc[2:, 4:]

nb_values_non_empty = week_values_stauro.notna().sum().sum()

print("Nombre de valeurs non vides dans Staurozoa :", nb_values_non_empty)

Nombre de valeurs non vides dans Staurozoa : 30

In [20]:
# Isoler les lignes Staurozoa avec des valeurs renseignées

stauro_values_df = tracking_long_df[
    (tracking_long_df["groupe"] == "Staurozoa")
    & (tracking_long_df["valeur"].notna())
].copy()

display(stauro_values_df)

stauro_values_df.to_csv(
    "staurozoa_a_verifier.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Lignes Staurozoa à vérifier :", stauro_values_df.shape)

,annee,groupe,espece,code_boite,temperature_cible,semaine,type_mesure,valeur,fichier_source,feuille_source,ligne_source
222995,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,20,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
222996,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,21,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
222997,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,22,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
222998,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,23,nb,3,Suivi_2025.xlsx,Staurozoa,3
222999,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,24,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223000,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,25,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223001,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,26,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223002,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,27,nb,3,Suivi_2025.xlsx,Staurozoa,3
223003,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,28,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223004,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,29,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223005,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,30,nb,3.0,Suivi_2025.xlsx,Staurozoa,3
223006,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,31,nb,2,Suivi_2025.xlsx,Staurozoa,3
223007,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,32,nb,2,Suivi_2025.xlsx,Staurozoa,3
223008,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,33,nb,1.0,Suivi_2025.xlsx,Staurozoa,3
223009,2025,Staurozoa,Lucernaria quadricornis,LQU-NBE-1.01,10,34,nb,0.0,Suivi_2025.xlsx,Staurozoa,3
223099,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.01,15,20,nb,1.0,Suivi_2025.xlsx,Staurozoa,5
223100,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.01,15,21,nb,0.0,Suivi_2025.xlsx,Staurozoa,5
223203,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,20,nb,3.0,Suivi_2025.xlsx,Staurozoa,7
223204,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,21,nb,3.0,Suivi_2025.xlsx,Staurozoa,7
223205,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,22,nb,3.0,Suivi_2025.xlsx,Staurozoa,7
223206,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,23,nb,3,Suivi_2025.xlsx,Staurozoa,7
223207,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,24,nb,3.0,Suivi_2025.xlsx,Staurozoa,7
223208,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,25,nb,3.0,Suivi_2025.xlsx,Staurozoa,7
223209,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,26,nb,3.0,Suivi_2025.xlsx,Staurozoa,7
223210,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,27,nb,3,Suivi_2025.xlsx,Staurozoa,7
223211,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,28,nb,3.0,Suivi_2025.xlsx,Staurozoa,7
223212,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,29,nb,3.0,Suivi_2025.xlsx,Staurozoa,7
223213,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,30,nb,3.0,Suivi_2025.xlsx,Staurozoa,7
223214,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,31,nb,2,Suivi_2025.xlsx,Staurozoa,7
223215,2025,Staurozoa,Staurozoa sp.,STA-FPA-1.02,15,32,nb,2,Suivi_2025.xlsx,Staurozoa,7

Lignes Staurozoa à vérifier : (30, 11)

In [21]:
# Correction spécifique pour Staurozoa :
# Dans cette feuille, les lignes "Nb" fonctionnent par paire :
# 1er Nb = polypes
# 2e Nb = ephyrules

tracking_long_df = tracking_long_df.sort_values(
    ["fichier_source", "feuille_source", "ligne_source", "semaine"]
).copy()

stauro_mask = (
    (tracking_long_df["groupe"] == "Staurozoa")
    & (tracking_long_df["type_mesure"] == "nb")
)

stauro_lignes = (
    tracking_long_df[stauro_mask][["fichier_source", "feuille_source", "ligne_source"]]
    .drop_duplicates()
    .sort_values(["fichier_source", "feuille_source", "ligne_source"])
    .reset_index(drop=True)
)

stauro_lignes["type_corrige"] = np.where(
    stauro_lignes.index % 2 == 0,
    "polypes",
    "ephyrules"
)

tracking_long_df = tracking_long_df.merge(
    stauro_lignes,
    on=["fichier_source", "feuille_source", "ligne_source"],
    how="left"
)

tracking_long_df["type_mesure"] = tracking_long_df["type_corrige"].fillna(
    tracking_long_df["type_mesure"]
)

tracking_long_df = tracking_long_df.drop(columns=["type_corrige"])

print(tracking_long_df["type_mesure"].value_counts(dropna=False))

type_mesure
polypes      130208
ephyrules    129480
Name: count, dtype: int64

In [22]:
clean_tracking_df = tracking_long_df.copy()

# Garder uniquement les lignes avec une valeur renseignée
clean_tracking_df = clean_tracking_df[clean_tracking_df["valeur"].notna()].copy()

# Garder uniquement les mesures exploitables
clean_tracking_df = clean_tracking_df[
    clean_tracking_df["type_mesure"].isin(["polypes", "ephyrules"])
].copy()

# Nettoyer les textes
for col in ["groupe", "espece", "code_boite", "fichier_source", "feuille_source"]:
    clean_tracking_df[col] = clean_tracking_df[col].astype("string").str.strip()

# Nettoyer les retours à la ligne dans les codes boîte
clean_tracking_df["code_boite"] = (
    clean_tracking_df["code_boite"]
    .str.replace("\n", "", regex=False)
    .str.replace("\r", "", regex=False)
    .str.strip()
)

# Convertir les valeurs en numérique
clean_tracking_df["valeur"] = pd.to_numeric(clean_tracking_df["valeur"], errors="coerce")

# Supprimer les valeurs non numériques
clean_tracking_df = clean_tracking_df[clean_tracking_df["valeur"].notna()].copy()

print("Données propres :", clean_tracking_df.shape)
print(clean_tracking_df["type_mesure"].value_counts(dropna=False))

print("Espèces manquantes :", clean_tracking_df["espece"].isna().sum())
print("Boîtes manquantes :", clean_tracking_df["code_boite"].isna().sum())
print("Températures manquantes :", clean_tracking_df["temperature_cible"].isna().sum())

Données propres : (76238, 11)
type_mesure
polypes      38223
ephyrules    38015
Name: count, dtype: int64
Espèces manquantes : 0
Boîtes manquantes : 0
Températures manquantes : 146

In [25]:
missing_temp_df = clean_tracking_df[
    clean_tracking_df["temperature_cible"].isna()
].copy()

display(missing_temp_df[[
    "annee",
    "groupe",
    "espece",
    "code_boite",
    "temperature_cible",
    "semaine",
    "type_mesure",
    "valeur",
    "fichier_source",
    "feuille_source",
    "ligne_source"
]].head(100))

print(missing_temp_df["fichier_source"].value_counts())
print(missing_temp_df["feuille_source"].value_counts())
print(missing_temp_df["code_boite"].value_counts().head(20))

,annee,groupe,espece,code_boite,temperature_cible,semaine,type_mesure,valeur,fichier_source,feuille_source,ligne_source
223288,2025,UMR_MARBEC,Rhizostoma pulmo,RPU-FBA-1.05,None,1,polypes,2.0,Suivi_2025.xlsx,UMR_MARBEC,3
223340,2025,UMR_MARBEC,Rhizostoma pulmo,RPU-FBA-1.05,None,1,ephyrules,0.0,Suivi_2025.xlsx,UMR_MARBEC,4
223496,2025,UMR_MARBEC,Rhizostoma pulmo,RPU-FBA-1.07,None,1,polypes,10.0,Suivi_2025.xlsx,UMR_MARBEC,7
223497,2025,UMR_MARBEC,Rhizostoma pulmo,RPU-FBA-1.07,None,2,polypes,19.0,Suivi_2025.xlsx,UMR_MARBEC,7
223498,2025,UMR_MARBEC,Rhizostoma pulmo,RPU-FBA-1.07,None,3,polypes,18.0,Suivi_2025.xlsx,UMR_MARBEC,7
...,...,...,...,...,...,...,...,...,...,...,...
223725,2025,UMR_MARBEC,Rhizostoma pulmo,RPU-FBA-1.08,None,22,polypes,9.0,Suivi_2025.xlsx,UMR_MARBEC,11
223726,2025,UMR_MARBEC,Rhizostoma pulmo,RPU-FBA-1.08,None,23,polypes,9.0,Suivi_2025.xlsx,UMR_MARBEC,11
223727,2025,UMR_MARBEC,Rhizostoma pulmo,RPU-FBA-1.08,None,24,polypes,9.0,Suivi_2025.xlsx,UMR_MARBEC,11
223728,2025,UMR_MARBEC,Rhizostoma pulmo,RPU-FBA-1.08,None,25,polypes,8.0,Suivi_2025.xlsx,UMR_MARBEC,11
223729,2025,UMR_MARBEC,Rhizostoma pulmo,RPU-FBA-1.08,None,26,polypes,10.0,Suivi_2025.xlsx,UMR_MARBEC,11

fichier_source
Suivi_2025.xlsx    146
Name: count, dtype: Int64
feuille_source
UMR_MARBEC    146
Name: count, dtype: Int64
code_boite
RPU-FBA-1.07    72
RPU-FBA-1.08    72
RPU-FBA-1.05     2
Name: count, dtype: Int64

In [26]:
# Export des lignes avec température manquante pour vérification manuelle

missing_temp_df = clean_tracking_df[
    clean_tracking_df["temperature_cible"].isna()
].copy()

missing_temp_df.to_csv(
    "anomalies_temperature_manquante.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Lignes avec température manquante exportées :", missing_temp_df.shape)

Lignes avec température manquante exportées : (146, 11)

In [33]:
# Table ESPECE

espece_df = (
    clean_tracking_df[["espece"]]
    .dropna()
    .drop_duplicates()
    .sort_values("espece")
    .reset_index(drop=True)
)

espece_df["id_espece"] = range(1, len(espece_df) + 1)

espece_df["code_espece"] = (
    espece_df["espece"]
    .str.upper()
    .str.replace(" ", "_", regex=False)
    .str.replace(".", "", regex=False)
)

espece_df = espece_df.rename(columns={
    "espece": "nom_scientifique"
})

espece_df = espece_df[[
    "id_espece",
    "code_espece",
    "nom_scientifique"
]]

display(espece_df)
print("Nombre d'espèces :", len(espece_df))

     id_espece            code_espece       nom_scientifique
0            1  ACROMITUS_FLAGELLATUS  Acromitus flagellatus
1            2  ACROMITUS_HARDENBERGI  Acromitus hardenbergi
2            3  AEQUOREA_COERULESCENS  Aequorea coerulescens
3            4  AEQUOREA_MACRODACTYLA  Aequorea macrodactyla
4            5      AEQUOREA_VICTORIA      Aequorea victoria
..         ...                    ...                    ...
143        144         TURRITOPSIS_SP        Turritopsis sp.
144        145       TURRITOPSIS_SP_1      Turritopsis sp. 1
145        146   VERSURIGA_ANADYOMENE   Versuriga anadyomene
146        147          ZANCLEIDAE_SP         Zancleidae sp.
147        148          EUDENDRYUM_SP          eudendryum sp

[148 rows x 3 columns]

Nombre d'espèces : 148

In [40]:
def extract_code_souche(code_boite):
    if pd.isna(code_boite):
        return None

    code_boite = str(code_boite).strip()

    # Exemple : ALA-JKA-1.02 -> ALA-JKA-1
    if "." in code_boite:
        return code_boite.split(".")[0]

    return code_boite


def extract_numero_souche_local(code_boite):
    if pd.isna(code_boite):
        return None

    parts = str(code_boite).strip().split("-")

    # Exemple : ALA-JKA-1.02 -> 1
    if len(parts) >= 3:
        return parts[2].split(".")[0]

    return None


def extract_provenance(code_boite):
    if pd.isna(code_boite):
        return None

    parts = str(code_boite).strip().split("-")

    # Exemple : ALA-JKA-1.02 -> JKA
    if len(parts) >= 2:
        return parts[1]

    return None


def extract_numero_boite_local(code_boite):
    if pd.isna(code_boite):
        return None

    code_boite = str(code_boite).strip()

    # Exemple : ALA-JKA-1.02 -> 02
    if "." in code_boite:
        return code_boite.split(".")[-1]

    return None

In [41]:
clean_tracking_df["code_souche"] = clean_tracking_df["code_boite"].apply(extract_code_souche)
clean_tracking_df["numero_souche_local"] = clean_tracking_df["code_boite"].apply(extract_numero_souche_local)
clean_tracking_df["code_provenance"] = clean_tracking_df["code_boite"].apply(extract_provenance)
clean_tracking_df["numero_boite_local"] = clean_tracking_df["code_boite"].apply(extract_numero_boite_local)

display(clean_tracking_df[[
    "code_boite",
    "code_souche",
    "numero_souche_local",
    "code_provenance",
    "numero_boite_local",
    "espece"
]].drop_duplicates().head(30))

,code_boite,code_souche,numero_souche_local,code_provenance,numero_boite_local,espece
21528,ALA-JKA-1.02,ALA-JKA-1,1,JKA,02,Aurelia labiata
21763,ALA-JKA-1.03,ALA-JKA-1,1,JKA,03,Aurelia labiata
21988,ALA-JKA-1.04,ALA-JKA-1,1,JKA,04,Aurelia labiata
22256,ALI-JKA-1.03,ALI-JKA-1,1,JKA,03,Aurelia limbata
22408,ALI-JKA-1.04,ALI-JKA-1,1,JKA,04,Aurelia limbata
22590,ALI-JKA-2.02,ALI-JKA-2,2,JKA,02,Aurelia limbata
22776,ALI-FPA-3.01,ALI-FPA-3,3,FPA,01,Aurelia limbata
23088,AMA-JKA-1.01,AMA-JKA-1,1,JKA,01,Aurelia maldivensis
23192,AMA-JKA-1.03,AMA-JKA-1,1,JKA,03,Aurelia maldivensis
23409,AMA-JKA-1.04,AMA-JKA-1,1,JKA,04,Aurelia maldivensis
23608,LAQ-JKA-1.01,LAQ-JKA-1,1,JKA,01,Linuche aquila
23834,LAQ-JKA-1.02,LAQ-JKA-1,1,JKA,02,Linuche aquila
24042,LUN-ESS-1.03,LUN-ESS-1,1,ESS,03,Linuche unguiculata
24232,LUN-ABR-2.01,LUN-ABR-2,2,ABR,01,Linuche unguiculata
24440,AMO-JKA-1.01,AMO-JKA-1,1,JKA,01,Alatina morandinii
24654,AMO-JKA-1.02,AMO-JKA-1,1,JKA,02,Alatina morandinii
24856,CMA-JKA-1.01,CMA-JKA-1,1,JKA,01,Carybdea marsupialis
24960,CMA-JKA-1.02,CMA-JKA-1,1,JKA,02,Carybdea marsupialis
25078,CMA-JKA-1.03,CMA-JKA-1,1,JKA,03,Carybdea marsupialis
25199,ACO-JKA-2.01,ACO-JKA-2,2,JKA,01,Aequorea coerulescens
25376,ACO-JKA-2.02,ACO-JKA-2,2,JKA,02,Aequorea coerulescens
25590,AVI-JKA-1.03,AVI-JKA-1,1,JKA,03,Aequorea victoria
25792,AVI-JKA-1.04,AVI-JKA-1,1,JKA,04,Aequorea victoria
26040,CLH-FVI-1.01,CLH-FVI-1,1,FVI,01,Clytia hemisphaerica
26352,CLH-FVI-1.02,CLH-FVI-1,1,FVI,02,Clytia hemisphaerica
26520,CSO-JKA-2.01,CSO-JKA-2,2,JKA,01,Craspedacusta sowerbii
26728,CSO-JKA-3.01,CSO-JKA-3,3,JKA,01,Craspedacusta sowerbii
26860,ELA-FPA-1.01,ELA-FPA-1,1,FPA,01,Eirene lacteoides
27040,ELA-FPA-1.02,ELA-FPA-1,1,FPA,02,Eirene lacteoides
27248,EIN-JKA-1.01,EIN-JKA-1,1,JKA,01,Eutonina indicans

In [42]:
# Table SOUCHE

souche_df = (
    clean_tracking_df[[
        "code_souche",
        "numero_souche_local",
        "espece"
    ]]
    .dropna(subset=["code_souche", "espece"])
    .drop_duplicates()
    .reset_index(drop=True)
)

souche_df = souche_df.merge(
    espece_df[["id_espece", "nom_scientifique"]],
    left_on="espece",
    right_on="nom_scientifique",
    how="left"
)

souche_df["id_souche"] = range(1, len(souche_df) + 1)
souche_df["nom_souche"] = souche_df["code_souche"]

souche_df = souche_df[[
    "id_souche",
    "code_souche",
    "numero_souche_local",
    "nom_souche",
    "id_espece"
]]

display(souche_df.head(20))
print("Nombre de souches :", len(souche_df))
print("Souches sans espèce liée :", souche_df["id_espece"].isna().sum())

    id_souche code_souche numero_souche_local nom_souche  id_espece
0           1   ALA-JKA-1                   1  ALA-JKA-1         14
1           2   ALI-JKA-1                   1  ALI-JKA-1         15
2           3   ALI-JKA-2                   2  ALI-JKA-2         15
3           4   ALI-FPA-3                   3  ALI-FPA-3         15
4           5   AMA-JKA-1                   1  AMA-JKA-1         17
5           6   LAQ-JKA-1                   1  LAQ-JKA-1         91
6           7   LUN-ESS-1                   1  LUN-ESS-1         94
7           8   LUN-ABR-2                   2  LUN-ABR-2         94
8           9   AMO-JKA-1                   1  AMO-JKA-1          9
9          10   CMA-JKA-1                   1  CMA-JKA-1         27
10         11   ACO-JKA-2                   2  ACO-JKA-2          3
11         12   AVI-JKA-1                   1  AVI-JKA-1          5
12         13   CLH-FVI-1                   1  CLH-FVI-1         56
13         14   CSO-JKA-2                   2  CSO-JKA-2         62
14         15   CSO-JKA-3                   3  CSO-JKA-3         62
15         16   ELA-FPA-1                   1  ELA-FPA-1         77
16         17   EIN-JKA-1                   1  EIN-JKA-1         79
17         18   LSP-FPA-1                   1  LSP-FPA-1         90
18         19   LSP-JKA-1                   1  LSP-JKA-1         90
19         20   NBR-JKA-1                   1  NBR-JKA-1        104

Nombre de souches : 228
Souches sans espèce liée : 0

In [43]:
species_per_souche = (
    souche_df
    .groupby("code_souche")["id_espece"]
    .nunique()
    .reset_index(name="nb_especes")
    .sort_values("nb_especes", ascending=False)
)

display(species_per_souche[species_per_souche["nb_especes"] > 1])

    code_souche  nb_especes
32    CAC-JKA-2           3
111   EUD-EMU-1           2
130   LRO-MAL-1           2
76    CNO-JKA-1           2
19    AMO-JKA-1           2
25    ATH-THA-1           2
47    CFU-JKA-2           2
27    AVA-TAI-1           2
147   OCE-TAI-1           2
197   THY-FGU-1           2
42    CCP-TPR-1           2
183   SME-JKA-1           2
200   TMU-JKA-2           2
181   SMA-MAU-3           2
66    CLH-FVI-1           2
65    CLA-NBE-5           2
63    CLA-JKA-4           2
180   SMA-JKA-2           2

In [44]:
# Voir le détail des souches associées à plusieurs espèces

problem_souches = species_per_souche[
    species_per_souche["nb_especes"] > 1
]["code_souche"].tolist()

problem_details_df = (
    clean_tracking_df[
        clean_tracking_df["code_souche"].isin(problem_souches)
    ][[
        "code_souche",
        "code_boite",
        "espece",
        "fichier_source",
        "feuille_source"
    ]]
    .drop_duplicates()
    .sort_values(["code_souche", "espece", "code_boite"])
)

display(problem_details_df)

,code_souche,code_boite,espece,fichier_source,feuille_source
151532,AMO-JKA-1,AMO-JKA-1.06,Alatina morandini,Suivi_2024.xlsx,Cubozoa
151736,AMO-JKA-1,AMO-JKA-1.07,Alatina morandini,Suivi_2024.xlsx,Cubozoa
152075,AMO-JKA-1,AMO-JKA-1.08,Alatina morandini,Suivi_2024.xlsx,Cubozoa
24440,AMO-JKA-1,AMO-JKA-1.01,Alatina morandinii,Suivi_2020.xlsx,Cubozoa
49300,AMO-JKA-1,AMO-JKA-1.01,Alatina morandinii,Suivi_2021.xlsx,Cubozoa
...,...,...,...,...,...
86370,TMU-JKA-2,TMU-JKA-2.01,Tiaropsis multicirrata,Suivi_2022.xlsx,Hydrozoa
125008,TMU-JKA-2,TMU-JKA-2.01,Tiaropsis multicirrata,Suivi_2023.xlsx,Hydrozoa
125242,TMU-JKA-2,TMU-JKA-2.02,Tiaropsis multicirrata,Suivi_2023.xlsx,Hydrozoa
161623,TMU-JKA-2,TMU-JKA-2.03,Tiarropsis multicirrata,Suivi_2024.xlsx,Hydrozoa
202072,TMU-JKA-2,TMU-JKA-2.03,Tiarropsis multicirrata,Suivi_2025.xlsx,Hydrozoa

In [45]:
species_corrections = {
    "Alatina morandini": "Alatina morandinii",
    "Tiarropsis multicirrata": "Tiaropsis multicirrata",
}

In [46]:
clean_tracking_df["espece"] = (
    clean_tracking_df["espece"]
    .replace(species_corrections)
)

In [47]:
# Recréer ESPECE après correction des noms

espece_df = (
    clean_tracking_df[["espece"]]
    .dropna()
    .drop_duplicates()
    .sort_values("espece")
    .reset_index(drop=True)
)

espece_df["id_espece"] = range(1, len(espece_df) + 1)

espece_df["code_espece"] = (
    espece_df["espece"]
    .str.upper()
    .str.replace(" ", "_", regex=False)
    .str.replace(".", "", regex=False)
)

espece_df = espece_df.rename(columns={
    "espece": "nom_scientifique"
})

espece_df = espece_df[[
    "id_espece",
    "code_espece",
    "nom_scientifique"
]]

print("Nombre d'espèces :", len(espece_df))
display(espece_df)

Nombre d'espèces : 146

     id_espece            code_espece       nom_scientifique
0            1  ACROMITUS_FLAGELLATUS  Acromitus flagellatus
1            2  ACROMITUS_HARDENBERGI  Acromitus hardenbergi
2            3  AEQUOREA_COERULESCENS  Aequorea coerulescens
3            4  AEQUOREA_MACRODACTYLA  Aequorea macrodactyla
4            5      AEQUOREA_VICTORIA      Aequorea victoria
..         ...                    ...                    ...
141        142         TURRITOPSIS_SP        Turritopsis sp.
142        143       TURRITOPSIS_SP_1      Turritopsis sp. 1
143        144   VERSURIGA_ANADYOMENE   Versuriga anadyomene
144        145          ZANCLEIDAE_SP         Zancleidae sp.
145        146          EUDENDRYUM_SP          eudendryum sp

[146 rows x 3 columns]

In [48]:
souche_df = (
    clean_tracking_df[[
        "code_souche",
        "numero_souche_local",
        "espece"
    ]]
    .dropna(subset=["code_souche", "espece"])
    .drop_duplicates()
    .reset_index(drop=True)
)

souche_df = souche_df.merge(
    espece_df[["id_espece", "nom_scientifique"]],
    left_on="espece",
    right_on="nom_scientifique",
    how="left"
)

souche_df["id_souche"] = range(1, len(souche_df) + 1)
souche_df["nom_souche"] = souche_df["code_souche"]

souche_df = souche_df[[
    "id_souche",
    "code_souche",
    "numero_souche_local",
    "nom_souche",
    "id_espece"
]]

print("Nombre de souches :", len(souche_df))
print("Souches sans espèce liée :", souche_df["id_espece"].isna().sum())
display(souche_df.head(20))

Nombre de souches : 226
Souches sans espèce liée : 0

    id_souche code_souche numero_souche_local nom_souche  id_espece
0           1   ALA-JKA-1                   1  ALA-JKA-1         13
1           2   ALI-JKA-1                   1  ALI-JKA-1         14
2           3   ALI-JKA-2                   2  ALI-JKA-2         14
3           4   ALI-FPA-3                   3  ALI-FPA-3         14
4           5   AMA-JKA-1                   1  AMA-JKA-1         16
5           6   LAQ-JKA-1                   1  LAQ-JKA-1         90
6           7   LUN-ESS-1                   1  LUN-ESS-1         93
7           8   LUN-ABR-2                   2  LUN-ABR-2         93
8           9   AMO-JKA-1                   1  AMO-JKA-1          8
9          10   CMA-JKA-1                   1  CMA-JKA-1         26
10         11   ACO-JKA-2                   2  ACO-JKA-2          3
11         12   AVI-JKA-1                   1  AVI-JKA-1          5
12         13   CLH-FVI-1                   1  CLH-FVI-1         55
13         14   CSO-JKA-2                   2  CSO-JKA-2         61
14         15   CSO-JKA-3                   3  CSO-JKA-3         61
15         16   ELA-FPA-1                   1  ELA-FPA-1         76
16         17   EIN-JKA-1                   1  EIN-JKA-1         78
17         18   LSP-FPA-1                   1  LSP-FPA-1         89
18         19   LSP-JKA-1                   1  LSP-JKA-1         89
19         20   NBR-JKA-1                   1  NBR-JKA-1        103

In [49]:
species_per_souche = (
    souche_df
    .groupby("code_souche")["id_espece"]
    .nunique()
    .reset_index(name="nb_especes")
    .sort_values("nb_especes", ascending=False)
)

display(species_per_souche[species_per_souche["nb_especes"] > 1])

    code_souche  nb_especes
32    CAC-JKA-2           3
183   SME-JKA-1           2
76    CNO-JKA-1           2
42    CCP-TPR-1           2
25    ATH-THA-1           2
47    CFU-JKA-2           2
147   OCE-TAI-1           2
197   THY-FGU-1           2
27    AVA-TAI-1           2
130   LRO-MAL-1           2
66    CLH-FVI-1           2
65    CLA-NBE-5           2
181   SMA-MAU-3           2
63    CLA-JKA-4           2
180   SMA-JKA-2           2
111   EUD-EMU-1           2

In [50]:
problem_souches = species_per_souche[
    species_per_souche["nb_especes"] > 1
]["code_souche"].tolist()

problem_details_df = (
    clean_tracking_df[
        clean_tracking_df["code_souche"].isin(problem_souches)
    ][[
        "code_souche",
        "code_boite",
        "espece",
        "fichier_source",
        "feuille_source"
    ]]
    .drop_duplicates()
    .sort_values(["code_souche", "espece", "code_boite"])
)

display(problem_details_df)

,code_souche,code_boite,espece,fichier_source,feuille_source
187453,ATH-THA-1,ATH-THA-1.01,Aurelia sp. THAI,Suivi_2025.xlsx,Aurelia
227552,ATH-THA-1,ATH-THA-1.01,Aurelia sp.4,Suivi_2026.xlsx,Aurelia
226512,AVA-TAI-1,AVA-TAI-1.01,Aurelia malayensis,Suivi_2026.xlsx,Aurelia
226824,AVA-TAI-1,AVA-TAI-1.02,Aurelia malayensis,Suivi_2026.xlsx,Aurelia
149701,AVA-TAI-1,AVA-TAI-1.01,"Aurelia sp.2 ""Valentine""",Suivi_2024.xlsx,Aurelia
...,...,...,...,...,...
63444,SME-JKA-1,SME-JKA-1.01,Stomolophus sp.2,Suivi_2021.xlsx,Rhizostomae
63648,SME-JKA-1,SME-JKA-1.04,Stomolophus sp.2,Suivi_2021.xlsx,Rhizostomae
63990,SME-JKA-1,SME-JKA-1.05,Stomolophus sp.2,Suivi_2021.xlsx,Rhizostomae
201884,THY-FGU-1,THY-FGU-1.01,Thyroscyphus sp.1 (white),Suivi_2025.xlsx,Hydrozoa
201988,THY-FGU-1,THY-FGU-1.01,Thyroscyphus sp.2 (red),Suivi_2025.xlsx,Hydrozoa

In [51]:
species_variants_df = (
    problem_details_df[["code_souche", "espece"]]
    .drop_duplicates()
    .sort_values(["code_souche", "espece"])
)

display(species_variants_df)

       code_souche                         espece
187453   ATH-THA-1               Aurelia sp. THAI
227552   ATH-THA-1                   Aurelia sp.4
226512   AVA-TAI-1             Aurelia malayensis
149701   AVA-TAI-1       Aurelia sp.2 "Valentine"
99370    CAC-JKA-2               Chrysaoa achlyos
134368   CAC-JKA-2              Chrysaora achlyos
252517   CAC-JKA-2  Chrysaora chesapeakei "white"
38615    CCP-TPR-1          Chrysaora chesapeakei
214552   CCP-TPR-1  Chrysaora chesapeakei "white"
39661    CFU-JKA-2           Chrysaora fuscescens
128587   CFU-JKA-2        Cotylorhiza tuberculata
178672   CLA-JKA-4                Cyanea lamarcki
109146   CLA-JKA-4               Cyanea lamarckii
220499   CLA-NBE-5                Cyanea lamarcki
257712   CLA-NBE-5               Cyanea lamarckii
26040    CLH-FVI-1           Clytia hemisphaerica
51168    CLH-FVI-1            Clytia hemispherica
220688   CNO-JKA-1                 Cyanea nozakii
44304    CNO-JKA-1      Cyanea nozakii Kishinouye
195857   EUD-EMU-1                 Eudendrium sp.
195909   EUD-EMU-1                  eudendryum sp
245336   LRO-MAL-1          Lobonemoides gracilis
207629   LRO-MAL-1          Lobonemoides robustus
200328   OCE-TAI-1                 Oceaniidae sp.
240240   OCE-TAI-1              Pennaria disticha
45808    SMA-JKA-2            Sanderia malayensis
180774   SMA-JKA-2    Sanderia malayensis "brown"
112475   SMA-MAU-3            Sanderia malayensis
181168   SMA-MAU-3    Sanderia malayensis "white"
37440    SME-JKA-1          Stomolophus meleagris
63444    SME-JKA-1               Stomolophus sp.2
201884   THY-FGU-1      Thyroscyphus sp.1 (white)
201988   THY-FGU-1        Thyroscyphus sp.2 (red)

In [54]:
species_corrections.update({
    "Chrysaoa achlyos": "Chrysaora achlyos",
    "Cyanea lamarcki": "Cyanea lamarckii",
    "Clytia hemispherica": "Clytia hemisphaerica",
    "Cyanea nozakii Kishinouye": "Cyanea nozakii",
    "eudendryum sp": "Eudendrium sp.",
})

In [55]:
clean_tracking_df["espece"] = clean_tracking_df["espece"].replace(species_corrections)

In [56]:
# Recréer ESPECE après correction des noms d'espèces

espece_df = (
    clean_tracking_df[["espece"]]
    .dropna()
    .drop_duplicates()
    .sort_values("espece")
    .reset_index(drop=True)
)

espece_df["id_espece"] = range(1, len(espece_df) + 1)

espece_df["code_espece"] = (
    espece_df["espece"]
    .str.upper()
    .str.replace(" ", "_", regex=False)
    .str.replace(".", "", regex=False)
)

espece_df = espece_df.rename(columns={
    "espece": "nom_scientifique"
})

espece_df = espece_df[[
    "id_espece",
    "code_espece",
    "nom_scientifique"
]]

print("Nombre d'espèces :", len(espece_df))
display(espece_df)

Nombre d'espèces : 141

     id_espece            code_espece       nom_scientifique
0            1  ACROMITUS_FLAGELLATUS  Acromitus flagellatus
1            2  ACROMITUS_HARDENBERGI  Acromitus hardenbergi
2            3  AEQUOREA_COERULESCENS  Aequorea coerulescens
3            4  AEQUOREA_MACRODACTYLA  Aequorea macrodactyla
4            5      AEQUOREA_VICTORIA      Aequorea victoria
..         ...                    ...                    ...
136        137   TURRITOPSIS_PACIFICA   Turritopsis pacifica
137        138         TURRITOPSIS_SP        Turritopsis sp.
138        139       TURRITOPSIS_SP_1      Turritopsis sp. 1
139        140   VERSURIGA_ANADYOMENE   Versuriga anadyomene
140        141          ZANCLEIDAE_SP         Zancleidae sp.

[141 rows x 3 columns]

In [57]:
# Recréer SOUCHE après correction des noms d'espèces

souche_df = (
    clean_tracking_df[[
        "code_souche",
        "numero_souche_local",
        "espece"
    ]]
    .dropna(subset=["code_souche", "espece"])
    .drop_duplicates()
    .reset_index(drop=True)
)

souche_df = souche_df.merge(
    espece_df[["id_espece", "nom_scientifique"]],
    left_on="espece",
    right_on="nom_scientifique",
    how="left"
)

souche_df["id_souche"] = range(1, len(souche_df) + 1)
souche_df["nom_souche"] = souche_df["code_souche"]

souche_df = souche_df[[
    "id_souche",
    "code_souche",
    "numero_souche_local",
    "nom_souche",
    "id_espece"
]]

print("Nombre de souches :", len(souche_df))
print("Souches sans espèce liée :", souche_df["id_espece"].isna().sum())
display(souche_df.head(20))

Nombre de souches : 220
Souches sans espèce liée : 0

    id_souche code_souche numero_souche_local nom_souche  id_espece
0           1   ALA-JKA-1                   1  ALA-JKA-1         13
1           2   ALI-JKA-1                   1  ALI-JKA-1         14
2           3   ALI-JKA-2                   2  ALI-JKA-2         14
3           4   ALI-FPA-3                   3  ALI-FPA-3         14
4           5   AMA-JKA-1                   1  AMA-JKA-1         16
5           6   LAQ-JKA-1                   1  LAQ-JKA-1         86
6           7   LUN-ESS-1                   1  LUN-ESS-1         89
7           8   LUN-ABR-2                   2  LUN-ABR-2         89
8           9   AMO-JKA-1                   1  AMO-JKA-1          8
9          10   CMA-JKA-1                   1  CMA-JKA-1         26
10         11   ACO-JKA-2                   2  ACO-JKA-2          3
11         12   AVI-JKA-1                   1  AVI-JKA-1          5
12         13   CLH-FVI-1                   1  CLH-FVI-1         54
13         14   CSO-JKA-2                   2  CSO-JKA-2         59
14         15   CSO-JKA-3                   3  CSO-JKA-3         59
15         16   ELA-FPA-1                   1  ELA-FPA-1         72
16         17   EIN-JKA-1                   1  EIN-JKA-1         74
17         18   LSP-FPA-1                   1  LSP-FPA-1         85
18         19   LSP-JKA-1                   1  LSP-JKA-1         85
19         20   NBR-JKA-1                   1  NBR-JKA-1         99

In [59]:
species_per_souche = (
    clean_tracking_df[["code_souche", "espece"]]
    .drop_duplicates()
    .groupby("code_souche")["espece"]
    .nunique()
    .reset_index(name="nb_especes")
    .sort_values("nb_especes", ascending=False)
)

display(species_per_souche[species_per_souche["nb_especes"] > 1])

    code_souche  nb_especes
32    CAC-JKA-2           2
27    AVA-TAI-1           2
197   THY-FGU-1           2
47    CFU-JKA-2           2
130   LRO-MAL-1           2
25    ATH-THA-1           2
147   OCE-TAI-1           2
183   SME-JKA-1           2
181   SMA-MAU-3           2
180   SMA-JKA-2           2
42    CCP-TPR-1           2

In [60]:
# Export des souches associées à plusieurs espèces restantes

problem_souches = species_per_souche[
    species_per_souche["nb_especes"] > 1
]["code_souche"].tolist()

problem_details_df = (
    clean_tracking_df[
        clean_tracking_df["code_souche"].isin(problem_souches)
    ][[
        "code_souche",
        "code_boite",
        "espece",
        "fichier_source",
        "feuille_source"
    ]]
    .drop_duplicates()
    .sort_values(["code_souche", "espece", "code_boite"])
)

problem_details_df.to_csv(
    "anomalies_souche_plusieurs_especes.csv",
    index=False,
    encoding="utf-8-sig"
)

display(problem_details_df)
print("Nombre de souches ambiguës :", len(problem_souches))

,code_souche,code_boite,espece,fichier_source,feuille_source
187453,ATH-THA-1,ATH-THA-1.01,Aurelia sp. THAI,Suivi_2025.xlsx,Aurelia
227552,ATH-THA-1,ATH-THA-1.01,Aurelia sp.4,Suivi_2026.xlsx,Aurelia
226512,AVA-TAI-1,AVA-TAI-1.01,Aurelia malayensis,Suivi_2026.xlsx,Aurelia
226824,AVA-TAI-1,AVA-TAI-1.02,Aurelia malayensis,Suivi_2026.xlsx,Aurelia
149701,AVA-TAI-1,AVA-TAI-1.01,"Aurelia sp.2 ""Valentine""",Suivi_2024.xlsx,Aurelia
...,...,...,...,...,...
63444,SME-JKA-1,SME-JKA-1.01,Stomolophus sp.2,Suivi_2021.xlsx,Rhizostomae
63648,SME-JKA-1,SME-JKA-1.04,Stomolophus sp.2,Suivi_2021.xlsx,Rhizostomae
63990,SME-JKA-1,SME-JKA-1.05,Stomolophus sp.2,Suivi_2021.xlsx,Rhizostomae
201884,THY-FGU-1,THY-FGU-1.01,Thyroscyphus sp.1 (white),Suivi_2025.xlsx,Hydrozoa
201988,THY-FGU-1,THY-FGU-1.01,Thyroscyphus sp.2 (red),Suivi_2025.xlsx,Hydrozoa

Nombre de souches ambiguës : 11

In [61]:
# Table BOITE

boite_df = (
    clean_tracking_df[[
        "code_boite",
        "code_souche",
        "numero_boite_local",
        "espece"
    ]]
    .dropna(subset=["code_boite", "code_souche", "espece"])
    .drop_duplicates()
    .reset_index(drop=True)
)

boite_df = boite_df.merge(
    espece_df[["id_espece", "nom_scientifique"]],
    left_on="espece",
    right_on="nom_scientifique",
    how="left"
)

boite_df = boite_df.merge(
    souche_df[["id_souche", "code_souche", "id_espece"]],
    on=["code_souche", "id_espece"],
    how="left"
)

boite_df["id_boite"] = range(1, len(boite_df) + 1)
boite_df["global_id"] = "POLYPBASE-" + boite_df["id_boite"].astype(str).str.zfill(6)
boite_df["code_local"] = boite_df["code_boite"]
boite_df["date_creation"] = None
boite_df["statut_boite"] = "historique"

boite_df = boite_df[[
    "id_boite",
    "global_id",
    "code_local",
    "numero_boite_local",
    "date_creation",
    "statut_boite",
    "id_souche"
]]

display(boite_df.head(20))
print("Nombre de boîtes :", len(boite_df))
print("Boîtes sans souche :", boite_df["id_souche"].isna().sum())

,id_boite,global_id,code_local,numero_boite_local,date_creation,statut_boite,id_souche
0,1,POLYPBASE-000001,ALA-JKA-1.02,02,None,historique,1
1,2,POLYPBASE-000002,ALA-JKA-1.03,03,None,historique,1
2,3,POLYPBASE-000003,ALA-JKA-1.04,04,None,historique,1
3,4,POLYPBASE-000004,ALI-JKA-1.03,03,None,historique,2
4,5,POLYPBASE-000005,ALI-JKA-1.04,04,None,historique,2
5,6,POLYPBASE-000006,ALI-JKA-2.02,02,None,historique,3
6,7,POLYPBASE-000007,ALI-FPA-3.01,01,None,historique,4
7,8,POLYPBASE-000008,AMA-JKA-1.01,01,None,historique,5
8,9,POLYPBASE-000009,AMA-JKA-1.03,03,None,historique,5
9,10,POLYPBASE-000010,AMA-JKA-1.04,04,None,historique,5
10,11,POLYPBASE-000011,LAQ-JKA-1.01,01,None,historique,6
11,12,POLYPBASE-000012,LAQ-JKA-1.02,02,None,historique,6
12,13,POLYPBASE-000013,LUN-ESS-1.03,03,None,historique,7
13,14,POLYPBASE-000014,LUN-ABR-2.01,01,None,historique,8
14,15,POLYPBASE-000015,AMO-JKA-1.01,01,None,historique,9
15,16,POLYPBASE-000016,AMO-JKA-1.02,02,None,historique,9
16,17,POLYPBASE-000017,CMA-JKA-1.01,01,None,historique,10
17,18,POLYPBASE-000018,CMA-JKA-1.02,02,None,historique,10
18,19,POLYPBASE-000019,CMA-JKA-1.03,03,None,historique,10
19,20,POLYPBASE-000020,ACO-JKA-2.01,01,None,historique,11

Nombre de boîtes : 589
Boîtes sans souche : 0

In [62]:
print("Doublons code_local :", boite_df["code_local"].duplicated().sum())

Doublons code_local : 14

In [63]:
doublon_boites_df = (
    boite_df[boite_df["code_local"].duplicated(keep=False)]
    .sort_values("code_local")
)

display(doublon_boites_df)
print("Nombre de lignes concernées :", len(doublon_boites_df))
print("Nombre de codes boîtes concernés :", doublon_boites_df["code_local"].nunique())

,id_boite,global_id,code_local,numero_boite_local,date_creation,statut_boite,id_souche
560,561,POLYPBASE-000561,ATH-THA-1.01,01,None,historique,214
458,459,POLYPBASE-000459,ATH-THA-1.01,01,None,historique,150
557,558,POLYPBASE-000558,AVA-TAI-1.01,01,None,historique,212
352,353,POLYPBASE-000353,AVA-TAI-1.01,01,None,historique,114
558,559,POLYPBASE-000559,AVA-TAI-1.02,02,None,historique,212
454,455,POLYPBASE-000455,AVA-TAI-1.02,02,None,historique,114
540,541,POLYPBASE-000541,CCP-TPR-1.08,08,None,historique,203
425,426,POLYPBASE-000426,CCP-TPR-1.08,08,None,historique,51
574,575,POLYPBASE-000575,LRO-MAL-1.01,01,None,historique,216
523,524,POLYPBASE-000524,LRO-MAL-1.01,01,None,historique,194
569,570,POLYPBASE-000570,OCE-TAI-1.02,02,None,historique,178
570,571,POLYPBASE-000571,OCE-TAI-1.02,02,None,historique,215
267,268,POLYPBASE-000268,SMA-JKA-2.05,05,None,historique,76
442,443,POLYPBASE-000443,SMA-JKA-2.05,05,None,historique,143
443,444,POLYPBASE-000444,SMA-JKA-2.06,06,None,historique,143
268,269,POLYPBASE-000269,SMA-JKA-2.06,06,None,historique,76
334,335,POLYPBASE-000335,SMA-MAU-3.02,02,None,historique,99
444,445,POLYPBASE-000445,SMA-MAU-3.02,02,None,historique,144
445,446,POLYPBASE-000446,SMA-MAU-3.03,03,None,historique,144
335,336,POLYPBASE-000336,SMA-MAU-3.03,03,None,historique,99
154,155,POLYPBASE-000155,SME-JKA-1.01,01,None,historique,80
81,82,POLYPBASE-000082,SME-JKA-1.01,01,None,historique,48
155,156,POLYPBASE-000156,SME-JKA-1.04,04,None,historique,80
82,83,POLYPBASE-000083,SME-JKA-1.04,04,None,historique,48
230,231,POLYPBASE-000231,SME-JKA-1.05,05,None,historique,48
156,157,POLYPBASE-000157,SME-JKA-1.05,05,None,historique,80
505,506,POLYPBASE-000506,THY-FGU-1.01,01,None,historique,183
506,507,POLYPBASE-000507,THY-FGU-1.01,01,None,historique,184

Nombre de lignes concernées : 28
Nombre de codes boîtes concernés : 14

In [64]:
codes_boites_doublons = doublon_boites_df["code_local"].unique()

details_doublon_boites_df = (
    clean_tracking_df[
        clean_tracking_df["code_boite"].isin(codes_boites_doublons)
    ][[
        "code_boite",
        "code_souche",
        "espece",
        "fichier_source",
        "feuille_source"
    ]]
    .drop_duplicates()
    .sort_values(["code_boite", "espece", "fichier_source"])
)

display(details_doublon_boites_df)

,code_boite,code_souche,espece,fichier_source,feuille_source
187453,ATH-THA-1.01,ATH-THA-1,Aurelia sp. THAI,Suivi_2025.xlsx,Aurelia
227552,ATH-THA-1.01,ATH-THA-1,Aurelia sp.4,Suivi_2026.xlsx,Aurelia
226512,AVA-TAI-1.01,AVA-TAI-1,Aurelia malayensis,Suivi_2026.xlsx,Aurelia
149701,AVA-TAI-1.01,AVA-TAI-1,"Aurelia sp.2 ""Valentine""",Suivi_2024.xlsx,Aurelia
186500,AVA-TAI-1.01,AVA-TAI-1,"Aurelia sp.2 ""Valentine""",Suivi_2025.xlsx,Aurelia
226824,AVA-TAI-1.02,AVA-TAI-1,Aurelia malayensis,Suivi_2026.xlsx,Aurelia
186689,AVA-TAI-1.02,AVA-TAI-1,"Aurelia sp.2 ""Valentine""",Suivi_2025.xlsx,Aurelia
173268,CCP-TPR-1.08,CCP-TPR-1,Chrysaora chesapeakei,Suivi_2024.xlsx,Semaestomeae
214552,CCP-TPR-1.08,CCP-TPR-1,"Chrysaora chesapeakei ""white""",Suivi_2025.xlsx,Semaestomeae
245336,LRO-MAL-1.01,LRO-MAL-1,Lobonemoides gracilis,Suivi_2026.xlsx,Rhizostomae
207629,LRO-MAL-1.01,LRO-MAL-1,Lobonemoides robustus,Suivi_2025.xlsx,Rhizostomae
240136,OCE-TAI-1.02,OCE-TAI-1,Oceaniidae sp.,Suivi_2026.xlsx,Hydrozoa
240240,OCE-TAI-1.02,OCE-TAI-1,Pennaria disticha,Suivi_2026.xlsx,Hydrozoa
111926,SMA-JKA-2.05,SMA-JKA-2,Sanderia malayensis,Suivi_2022.xlsx,Semaestomeae
143438,SMA-JKA-2.05,SMA-JKA-2,Sanderia malayensis,Suivi_2023.xlsx,Semaestomeae
180774,SMA-JKA-2.05,SMA-JKA-2,"Sanderia malayensis ""brown""",Suivi_2024.xlsx,Semaestomeae
222144,SMA-JKA-2.05,SMA-JKA-2,"Sanderia malayensis ""brown""",Suivi_2025.xlsx,Semaestomeae
258856,SMA-JKA-2.05,SMA-JKA-2,"Sanderia malayensis ""brown""",Suivi_2026.xlsx,Semaestomeae
112160,SMA-JKA-2.06,SMA-JKA-2,Sanderia malayensis,Suivi_2022.xlsx,Semaestomeae
143624,SMA-JKA-2.06,SMA-JKA-2,Sanderia malayensis,Suivi_2023.xlsx,Semaestomeae
180970,SMA-JKA-2.06,SMA-JKA-2,"Sanderia malayensis ""brown""",Suivi_2024.xlsx,Semaestomeae
222456,SMA-JKA-2.06,SMA-JKA-2,"Sanderia malayensis ""brown""",Suivi_2025.xlsx,Semaestomeae
259168,SMA-JKA-2.06,SMA-JKA-2,"Sanderia malayensis ""brown""",Suivi_2026.xlsx,Semaestomeae
144088,SMA-MAU-3.02,SMA-MAU-3,Sanderia malayensis,Suivi_2023.xlsx,Semaestomeae
181168,SMA-MAU-3.02,SMA-MAU-3,"Sanderia malayensis ""white""",Suivi_2024.xlsx,Semaestomeae
144400,SMA-MAU-3.03,SMA-MAU-3,Sanderia malayensis,Suivi_2023.xlsx,Semaestomeae
181398,SMA-MAU-3.03,SMA-MAU-3,"Sanderia malayensis ""white""",Suivi_2024.xlsx,Semaestomeae
222664,SMA-MAU-3.03,SMA-MAU-3,"Sanderia malayensis ""white""",Suivi_2025.xlsx,Semaestomeae
259376,SMA-MAU-3.03,SMA-MAU-3,"Sanderia malayensis ""white""",Suivi_2026.xlsx,Semaestomeae
37440,SME-JKA-1.01,SME-JKA-1,Stomolophus meleagris,Suivi_2020.xlsx,Rhizostomae
63444,SME-JKA-1.01,SME-JKA-1,Stomolophus sp.2,Suivi_2021.xlsx,Rhizostomae
37544,SME-JKA-1.04,SME-JKA-1,Stomolophus meleagris,Suivi_2020.xlsx,Rhizostomae
96616,SME-JKA-1.04,SME-JKA-1,Stomolophus meleagris,Suivi_2022.xlsx,Rhizostomae
132292,SME-JKA-1.04,SME-JKA-1,Stomolophus meleagris,Suivi_2023.xlsx,Rhizostomeae
63648,SME-JKA-1.04,SME-JKA-1,Stomolophus sp.2,Suivi_2021.xlsx,Rhizostomae
96928,SME-JKA-1.05,SME-JKA-1,Stomolophus meleagris,Suivi_2022.xlsx,Rhizostomae
63990,SME-JKA-1.05,SME-JKA-1,Stomolophus sp.2,Suivi_2021.xlsx,Rhizostomae
201884,THY-FGU-1.01,THY-FGU-1,Thyroscyphus sp.1 (white),Suivi_2025.xlsx,Hydrozoa
201988,THY-FGU-1.01,THY-FGU-1,Thyroscyphus sp.2 (red),Suivi_2025.xlsx,Hydrozoa

In [65]:
# Codes de boîtes associés à plusieurs espèces
codes_boites_ambiguës = details_doublon_boites_df["code_boite"].unique()

# Export des anomalies
details_doublon_boites_df.to_csv(
    "anomalies_boites_plusieurs_especes.csv",
    index=False,
    encoding="utf-8-sig"
)

# Séparer les données propres des données ambiguës
clean_tracking_valid_df = clean_tracking_df[
    ~clean_tracking_df["code_boite"].isin(codes_boites_ambiguës)
].copy()

clean_tracking_anomalies_df = clean_tracking_df[
    clean_tracking_df["code_boite"].isin(codes_boites_ambiguës)
].copy()

print("Lignes valides :", len(clean_tracking_valid_df))
print("Lignes mises en anomalie :", len(clean_tracking_anomalies_df))
print("Boîtes ambiguës :", len(codes_boites_ambiguës))

Lignes valides : 73807
Lignes mises en anomalie : 2431
Boîtes ambiguës : 14

In [66]:
boite_df = (
    clean_tracking_valid_df[[
        "code_boite",
        "code_souche",
        "numero_boite_local",
        "espece"
    ]]
    .dropna(subset=["code_boite", "code_souche", "espece"])
    .drop_duplicates()
    .reset_index(drop=True)
)

boite_df = boite_df.merge(
    espece_df[["id_espece", "nom_scientifique"]],
    left_on="espece",
    right_on="nom_scientifique",
    how="left"
)

boite_df = boite_df.merge(
    souche_df[["id_souche", "code_souche", "id_espece"]],
    on=["code_souche", "id_espece"],
    how="left"
)

boite_df["id_boite"] = range(1, len(boite_df) + 1)
boite_df["global_id"] = "POLYPBASE-" + boite_df["id_boite"].astype(str).str.zfill(6)
boite_df["code_local"] = boite_df["code_boite"]
boite_df["date_creation"] = None
boite_df["statut_boite"] = "historique"

boite_df = boite_df[[
    "id_boite",
    "global_id",
    "code_local",
    "numero_boite_local",
    "date_creation",
    "statut_boite",
    "id_souche"
]]

print("Nombre de boîtes valides :", len(boite_df))
print("Doublons code_local :", boite_df["code_local"].duplicated().sum())
print("Boîtes sans souche :", boite_df["id_souche"].isna().sum())

Nombre de boîtes valides : 561
Doublons code_local : 0
Boîtes sans souche : 0

In [67]:
# Préparer les relevés à partir des données valides uniquement

releve_base_df = clean_tracking_valid_df.merge(
    boite_df[["id_boite", "code_local"]],
    left_on="code_boite",
    right_on="code_local",
    how="left"
)

print("Lignes de relevés sans boîte :", releve_base_df["id_boite"].isna().sum())

Lignes de relevés sans boîte : 0

In [68]:
releve_df = (
    releve_base_df
    .pivot_table(
        index=["annee", "semaine", "id_boite"],
        columns="type_mesure",
        values="valeur",
        aggfunc="first"
    )
    .reset_index()
)

releve_df = releve_df.rename(columns={
    "polypes": "nombre_polypes",
    "ephyrules": "nombre_ephyrules"
})

releve_df["date_releve"] = (
    releve_df["annee"].astype(str)
    + "-S"
    + releve_df["semaine"].astype(int).astype(str).str.zfill(2)
)

releve_df["type_observation"] = "historique_excel"
releve_df["commentaire"] = None
releve_df["id_utilisateur"] = None

releve_df = releve_df[[
    "id_utilisateur",
    "id_boite",
    "date_releve",
    "nombre_polypes",
    "nombre_ephyrules",
    "type_observation",
    "commentaire"
]]

display(releve_df.head(20))
print("Nombre de relevés :", len(releve_df))
print("Relevés sans boîte :", releve_df["id_boite"].isna().sum())
print("Relevés sans polypes :", releve_df["nombre_polypes"].isna().sum())
print("Relevés sans éphyrules :", releve_df["nombre_ephyrules"].isna().sum())

type_mesure,id_utilisateur,id_boite,date_releve,nombre_polypes,nombre_ephyrules,type_observation,commentaire
0,None,1,2020-S01,200.0,200.0,historique_excel,None
1,None,2,2020-S01,50.0,0.0,historique_excel,None
2,None,4,2020-S01,200.0,0.0,historique_excel,None
3,None,6,2020-S01,100.0,0.0,historique_excel,None
4,None,7,2020-S01,200.0,200.0,historique_excel,None
5,None,8,2020-S01,200.0,0.0,historique_excel,None
6,None,9,2020-S01,200.0,0.0,historique_excel,None
7,None,11,2020-S01,50.0,0.0,historique_excel,None
8,None,12,2020-S01,100.0,0.0,historique_excel,None
9,None,13,2020-S01,200.0,0.0,historique_excel,None
10,None,14,2020-S01,2.0,0.0,historique_excel,None
11,None,15,2020-S01,200.0,3.0,historique_excel,None
12,None,16,2020-S01,200.0,50.0,historique_excel,None
13,None,17,2020-S01,200.0,50.0,historique_excel,None
14,None,18,2020-S01,200.0,50.0,historique_excel,None
15,None,20,2020-S01,100.0,0.0,historique_excel,None
16,None,21,2020-S01,100.0,0.0,historique_excel,None
17,None,22,2020-S01,200.0,0.0,historique_excel,None
18,None,23,2020-S01,200.0,0.0,historique_excel,None
19,None,26,2020-S01,50.0,0.0,historique_excel,None

Nombre de relevés : 36998
Relevés sans boîte : 0
Relevés sans polypes : 208
Relevés sans éphyrules : 290

In [69]:
display(
    releve_df[
        releve_df["nombre_polypes"].isna() | releve_df["nombre_ephyrules"].isna()
    ].head(30)
)

type_mesure,id_utilisateur,id_boite,date_releve,nombre_polypes,nombre_ephyrules,type_observation,commentaire
1130,None,12,2020-S15,NaN,0.0,historique_excel,None
8286,None,118,2021-S41,NaN,0.0,historique_excel,None
8386,None,118,2021-S42,NaN,0.0,historique_excel,None
8486,None,118,2021-S43,NaN,0.0,historique_excel,None
8560,None,83,2021-S44,NaN,0.0,historique_excel,None
8585,None,118,2021-S44,NaN,0.0,historique_excel,None
8604,None,144,2021-S44,NaN,50.0,historique_excel,None
8660,None,83,2021-S45,NaN,0.0,historique_excel,None
8685,None,118,2021-S45,NaN,0.0,historique_excel,None
8760,None,83,2021-S46,NaN,0.0,historique_excel,None
8785,None,118,2021-S46,NaN,0.0,historique_excel,None
8860,None,83,2021-S47,NaN,0.0,historique_excel,None
8885,None,118,2021-S47,NaN,0.0,historique_excel,None
8960,None,83,2021-S48,NaN,0.0,historique_excel,None
8985,None,118,2021-S48,NaN,0.0,historique_excel,None
9051,None,83,2021-S49,NaN,0.0,historique_excel,None
9073,None,118,2021-S49,NaN,0.0,historique_excel,None
9147,None,83,2021-S50,NaN,0.0,historique_excel,None
9169,None,118,2021-S50,NaN,0.0,historique_excel,None
9244,None,83,2021-S51,NaN,0.0,historique_excel,None
9266,None,118,2021-S51,NaN,0.0,historique_excel,None
9341,None,83,2021-S52,NaN,0.0,historique_excel,None
9363,None,118,2021-S52,NaN,0.0,historique_excel,None
14201,None,219,2023-S01,100.0,NaN,historique_excel,None
14298,None,219,2023-S02,200.0,NaN,historique_excel,None
14395,None,219,2023-S03,200.0,NaN,historique_excel,None
14492,None,219,2023-S04,300.0,NaN,historique_excel,None
14587,None,219,2023-S05,300.0,NaN,historique_excel,None
14683,None,219,2023-S06,300.0,NaN,historique_excel,None
14779,None,219,2023-S07,200.0,NaN,historique_excel,None

In [70]:
anomalies_releves_incomplets_df = releve_df[
    releve_df["nombre_polypes"].isna() | releve_df["nombre_ephyrules"].isna()
].copy()

anomalies_releves_incomplets_df.to_csv(
    "anomalies_releves_incomplets.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Relevés incomplets :", len(anomalies_releves_incomplets_df))

Relevés incomplets : 498

In [71]:
# Nettoyer les températures

clean_tracking_valid_df["temperature_cible"] = pd.to_numeric(
    clean_tracking_valid_df["temperature_cible"],
    errors="coerce"
)

zone_thermique_df = (
    clean_tracking_valid_df[["temperature_cible"]]
    .dropna()
    .drop_duplicates()
    .sort_values("temperature_cible")
    .reset_index(drop=True)
)

zone_thermique_df["id_zone"] = range(1, len(zone_thermique_df) + 1)

zone_thermique_df["nom_zone"] = (
    "Zone "
    + zone_thermique_df["temperature_cible"].astype(str)
    + "°C"
)

zone_thermique_df["type_zone"] = "historique_excel"

zone_thermique_df = zone_thermique_df[[
    "id_zone",
    "nom_zone",
    "type_zone",
    "temperature_cible"
]]

display(zone_thermique_df)
print("Nombre de zones thermiques :", len(zone_thermique_df))

   id_zone     nom_zone         type_zone  temperature_cible
0        1   Zone 5.0°C  historique_excel                5.0
1        2  Zone 10.0°C  historique_excel               10.0
2        3  Zone 15.0°C  historique_excel               15.0
3        4  Zone 20.0°C  historique_excel               20.0
4        5  Zone 25.0°C  historique_excel               25.0
5        6  Zone 30.0°C  historique_excel               30.0

Nombre de zones thermiques : 6

In [72]:
print(clean_tracking_valid_df["temperature_cible"].value_counts(dropna=False).sort_index())

temperature_cible
5.0      4069
10.0    10390
15.0    16711
20.0    18291
25.0    17153
30.0     6901
NaN       292
Name: count, dtype: int64

In [73]:
anomalies_temperature_valid_df = clean_tracking_valid_df[
    clean_tracking_valid_df["temperature_cible"].isna()
].copy()

anomalies_temperature_valid_df.to_csv(
    "anomalies_temperature_manquante_valides.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Lignes valides avec température manquante :", len(anomalies_temperature_valid_df))
display(anomalies_temperature_valid_df[[
    "code_boite",
    "espece",
    "annee",
    "semaine",
    "fichier_source",
    "feuille_source"
]].drop_duplicates().head(30))

Lignes valides avec température manquante : 292

,code_boite,espece,annee,semaine,fichier_source,feuille_source
183664,ACA-FBA-1.01,Aurelia coerulea,2025,1,Suivi_2025.xlsx,Aurelia
183665,ACA-FBA-1.01,Aurelia coerulea,2025,2,Suivi_2025.xlsx,Aurelia
183666,ACA-FBA-1.01,Aurelia coerulea,2025,3,Suivi_2025.xlsx,Aurelia
183667,ACA-FBA-1.01,Aurelia coerulea,2025,4,Suivi_2025.xlsx,Aurelia
183668,ACA-FBA-1.01,Aurelia coerulea,2025,5,Suivi_2025.xlsx,Aurelia
183669,ACA-FBA-1.01,Aurelia coerulea,2025,6,Suivi_2025.xlsx,Aurelia
183670,ACA-FBA-1.01,Aurelia coerulea,2025,7,Suivi_2025.xlsx,Aurelia
183671,ACA-FBA-1.01,Aurelia coerulea,2025,8,Suivi_2025.xlsx,Aurelia
183672,ACA-FBA-1.01,Aurelia coerulea,2025,9,Suivi_2025.xlsx,Aurelia
183673,ACA-FBA-1.01,Aurelia coerulea,2025,10,Suivi_2025.xlsx,Aurelia
183674,ACA-FBA-1.01,Aurelia coerulea,2025,11,Suivi_2025.xlsx,Aurelia
183675,ACA-FBA-1.01,Aurelia coerulea,2025,12,Suivi_2025.xlsx,Aurelia
183676,ACA-FBA-1.01,Aurelia coerulea,2025,13,Suivi_2025.xlsx,Aurelia
183677,ACA-FBA-1.01,Aurelia coerulea,2025,14,Suivi_2025.xlsx,Aurelia
183678,ACA-FBA-1.01,Aurelia coerulea,2025,15,Suivi_2025.xlsx,Aurelia
183679,ACA-FBA-1.01,Aurelia coerulea,2025,16,Suivi_2025.xlsx,Aurelia
183680,ACA-FBA-1.01,Aurelia coerulea,2025,17,Suivi_2025.xlsx,Aurelia
183681,ACA-FBA-1.01,Aurelia coerulea,2025,18,Suivi_2025.xlsx,Aurelia
183682,ACA-FBA-1.01,Aurelia coerulea,2025,19,Suivi_2025.xlsx,Aurelia
183683,ACA-FBA-1.01,Aurelia coerulea,2025,20,Suivi_2025.xlsx,Aurelia
183684,ACA-FBA-1.01,Aurelia coerulea,2025,21,Suivi_2025.xlsx,Aurelia
183685,ACA-FBA-1.01,Aurelia coerulea,2025,22,Suivi_2025.xlsx,Aurelia
183686,ACA-FBA-1.01,Aurelia coerulea,2025,23,Suivi_2025.xlsx,Aurelia
183687,ACA-FBA-1.01,Aurelia coerulea,2025,24,Suivi_2025.xlsx,Aurelia
183688,ACA-FBA-1.01,Aurelia coerulea,2025,25,Suivi_2025.xlsx,Aurelia
183689,ACA-FBA-1.01,Aurelia coerulea,2025,26,Suivi_2025.xlsx,Aurelia
183690,ACA-FBA-1.01,Aurelia coerulea,2025,27,Suivi_2025.xlsx,Aurelia
183691,ACA-FBA-1.01,Aurelia coerulea,2025,28,Suivi_2025.xlsx,Aurelia
183692,ACA-FBA-1.01,Aurelia coerulea,2025,29,Suivi_2025.xlsx,Aurelia
183693,ACA-FBA-1.01,Aurelia coerulea,2025,30,Suivi_2025.xlsx,Aurelia

In [74]:
range_base_df = clean_tracking_valid_df[
    clean_tracking_valid_df["temperature_cible"].notna()
].copy()

range_base_df = range_base_df.merge(
    boite_df[["id_boite", "code_local"]],
    left_on="code_boite",
    right_on="code_local",
    how="left"
)

range_base_df = range_base_df.merge(
    zone_thermique_df[["id_zone", "temperature_cible"]],
    on="temperature_cible",
    how="left"
)

range_df = (
    range_base_df[[
        "id_boite",
        "id_zone",
        "annee",
        "semaine"
    ]]
    .dropna(subset=["id_boite", "id_zone"])
    .drop_duplicates()
    .reset_index(drop=True)
)

range_df["date_entree"] = (
    range_df["annee"].astype(str)
    + "-S"
    + range_df["semaine"].astype(int).astype(str).str.zfill(2)
)

range_df["date_sortie"] = None
range_df["motif"] = "historique_excel"
range_df["id_utilisateur"] = None

range_df = range_df[[
    "id_utilisateur",
    "id_boite",
    "id_zone",
    "date_entree",
    "date_sortie",
    "motif"
]]

display(range_df.head(20))
print("Nombre de rangements :", len(range_df))
print("Rangements sans boîte :", range_df["id_boite"].isna().sum())
print("Rangements sans zone :", range_df["id_zone"].isna().sum())

   id_utilisateur  id_boite  id_zone date_entree date_sortie             motif
0            None         1        1    2020-S01        None  historique_excel
1            None         1        1    2020-S02        None  historique_excel
2            None         1        1    2020-S03        None  historique_excel
3            None         1        1    2020-S04        None  historique_excel
4            None         1        1    2020-S05        None  historique_excel
5            None         1        1    2020-S06        None  historique_excel
6            None         1        1    2020-S07        None  historique_excel
7            None         1        1    2020-S08        None  historique_excel
8            None         1        1    2020-S09        None  historique_excel
9            None         1        1    2020-S10        None  historique_excel
10           None         1        1    2020-S11        None  historique_excel
11           None         1        1    2020-S15        None  historique_excel
12           None         1        1    2020-S19        None  historique_excel
13           None         1        1    2020-S23        None  historique_excel
14           None         1        1    2020-S24        None  historique_excel
15           None         1        1    2020-S25        None  historique_excel
16           None         1        1    2020-S27        None  historique_excel
17           None         1        3    2020-S28        None  historique_excel
18           None         1        3    2020-S29        None  historique_excel
19           None         1        3    2020-S30        None  historique_excel

Nombre de rangements : 36881
Rangements sans boîte : 0
Rangements sans zone : 0

In [75]:
OUTPUT_DIR = DATA_DIR / "exports_polypbase"
OUTPUT_DIR.mkdir(exist_ok=True)

espece_df.to_csv(OUTPUT_DIR / "espece.csv", index=False, encoding="utf-8-sig")
souche_df.to_csv(OUTPUT_DIR / "souche.csv", index=False, encoding="utf-8-sig")
boite_df.to_csv(OUTPUT_DIR / "boite.csv", index=False, encoding="utf-8-sig")
releve_df.to_csv(OUTPUT_DIR / "saisir_releve.csv", index=False, encoding="utf-8-sig")
zone_thermique_df.to_csv(OUTPUT_DIR / "zone_thermique.csv", index=False, encoding="utf-8-sig")
range_df.to_csv(OUTPUT_DIR / "range.csv", index=False, encoding="utf-8-sig")

print("Exports terminés dans :", OUTPUT_DIR)

Exports terminés dans : /Users/akkouh/Desktop/polybase/exports_polypbase